### ISSUE TITLE
Using a Function constructor might be dangerous

### ISSUE THREAD

**Issue by julian-r** [mikemaccana/dynamic-template#2]
an can lead to XSS vulnerabilities. This is an example how this can happen:

https://jsfiddle.net/Lamik/w97qdpvf/

So you should point this out in your module description.

**Comment by julian-r** [comment]
This is a nice a solution you could use. IT would fix your security issue :) 
https://stackoverflow.com/questions/30003353/can-es6-template-literals-be-substituted-at-runtime-or-reused#answer-55594573

**Comment by mikemaccana** [comment]
@julian-r Yes, accepting unsanitised input from users anywhere is a security issue. I'll add a note to the README pointing this out.

**Comment by julian-r** [comment]
Usually this is only the case if you eval anything, and here is even a fix.

**Comment by mikemaccana** [comment]
No, displaying any unsanitized input would allow XSS.
